version: '3.8'

services:
  db:
    container_name: medo-com-db
    image: postgres
    restart: always
    ports:
      - 2010:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - medo-com-db:/var/lib/postgresql/data
volumes:
  medo-com-db: